# Generated by Django 3.2.25 on 2025-06-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cartelera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartelera',
            name='imagen',
        ),
    ]
