# Generated by Django 3.2.25 on 2025-06-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_cartelera_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartelera',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
