# Generated by Django 3.2.25 on 2025-06-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cartelera_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartelera',
            name='nombre_de_la_pelicula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartelera',
            name='titulo',
            field=models.TextField(),
        ),
    ]
