# Generated by Django 3.2.25 on 2025-06-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20250619_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartelera',
            name='titulo',
        ),
        migrations.AddField(
            model_name='cartelera',
            name='clasificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartelera',
            name='esteno_duracion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartelera',
            name='reseña',
            field=models.TextField(blank=True, null=True),
        ),
    ]
