# Generated by Django 3.2.25 on 2025-06-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20250619_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartelera',
            old_name='esteno_duracion',
            new_name='estreno_duracion',
        ),
    ]
