# Generated by Django 3.2.25 on 2025-06-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_esteno_duracion_cartelera_estreno_duracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartelera',
            old_name='estreno_duracion',
            new_name='estreno_categoria_duracion',
        ),
    ]
